### ISSUE TITLE
Support passing options

### ISSUE THREAD

**Issue by odow** [odow/NEOS.jl#35]
https://github.com/odow/NEOSServer.jl/blob/0d8f635df8049d90b78c5e9f177e3915906cd7ec/src/NEOSServer.jl#L229

**Comment by avinashresearch1** [comment]
@odow Thanks for the excellent package! Since time limits are so crucial for NEOS, I was wondering if there is a general way to set them. I see that we can pass a `kwarg` but the time limit setting is solver dependent and I can't find any information on how to set a limit for  say OCTERACT. 

I assumed sth like:
```
model = Model() do
    NEOSServer.Optimizer(email=NEOS_email, solver=NEOS_solver, solver_args = ["octeract_engine.time_limit=10.0"]) 
end
```

with this ammendment to add `solver_args` 
```
function Optimizer(; email::String, solver::String, solver_args = String[], kwargs...)
    category = get(_SUPPORTED_SOLVERS, solver, nothing)
    if category === nothing
        error(
            "NEOS.Optimizer only supports the following solvers: " *
            join(collect(keys(_SUPPORTED_SOLVERS)), ", "),
        )
    end
    cmd = _SolverCommand(solver, category, Server(email))
    return AmplNLWriter.Optimizer(cmd, solver_args; kwargs...)
end
```
But I realize that options are neglected in formulating the XML file.

**Comment by odow** [comment]
It's been a while since I looked at this, so I don't remember why options weren't trivial. Not sure if I have an ETA to implement this sorry.

**Comment by gnowzil** [comment]
@odow can you check if options are working now?  had to change option processing on the NEOS end for NL and it's a bit tricky so let me know if it's not working properly.  thanks!

**Comment by odow** [comment]
Thanks @gnowzil, added here: https://github.com/odow/NEOSServer.jl/pull/43.

Tests check that passing options work (for Ipopt, at least).

We currently pass them as they would be written in a `.opt` file. So `option value` separated by a space, with new lines separating multiple options.
